### ISSUE TITLE
Lightbox overlay duplicates when using turbolinks

### ISSUE THREAD

**Issue by nudzg** [gavinkflam/lightbox2-rails#1]
How to reproduce:
1. Load page
2. Follow some (internal) link (this time, page is loaded using turbolinks). It's working nice at this point.
3. Follow another (internal) link
4. Now there's another div#lightboxOverlay and div#lightbox at the bottom of body and the browser is showing the spinner inside the empty overlay.

Javascript is included at the bottom of body:

```
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
```

A workaround that worked for me was adding div#lightbox-container at the top of the body and modify lightbox.js in Lightbox.prototype.build function:

```
$('#lightbox-container').html('');
$("<div id='lightboxOverlay' class='lightboxOverlay'></div><div id='lightbox' class='lightbox'><div class='lb-outerContainer'><div class='lb-container'><img class='lb-image' src='' /><div class='lb-nav'><a class='lb-prev' href='' ></a><a class='lb-next' href='' ></a></div><div class='lb-loader'><a class='lb-cancel'></a></div></div></div><div class='lb-dataContainer'><div class='lb-data'><div class='lb-details'><span class='lb-caption'></span><span class='lb-number'></span></div><div class='lb-closeContainer'><a class='lb-close'></a></div></div></div></div>").appendTo($('#lightbox-container'));
```

I was unable to find anything better :-(

**Comment by gavinkflam** [comment]
Sorry but I cannot reproduce the issue described.
What version of jQuery and Turbolinks are you using?

**Comment by gavinkflam** [comment]
According to my understanding, the `javascript_include_tag` should be added in the head section for Turbolinks enabled site. It should be the source of error.

**Comment by dan1d** [comment]
@nudzg did you found another solution?
