### ISSUE TITLE
Pass over the owner ship of the gem

### ISSUE THREAD

**Issue by johansmitsnl** [gavinkflam/lightbox2-rails#14]
We had a conversation by email that you no longer have a active project with lightbox.
I'm more then happy to take over the ownership of the gem.
Please add me as the new oner on rubygems.

**Comment by benbarber** [comment]
@johansmitsnl I would open an issue with Ruby Gems directly and see what they can do, as your fork works and this repo does not. The repo owner clearly can't be arsed to merge in your pull request or reply to you. http://help.rubygems.org/discussion/new

**Comment by johansmitsnl** [comment]
@benbarber that sounds good. Let me know what the outcome is.

**Comment by johansmitsnl** [comment]
@benbarber any news?

**Comment by benbarber** [comment]
@johansmitsnl Unfortunately not, I did open an issue with Ruby Gems Support but have had no response.

**Comment by gavinkflam** [comment]
I will be adding CI/CD and publish a newer version with Lightbox 2.10.0.
Sorry for abandoned the project and caused the troubles. I have not been using Rails since then.

**Comment by johansmitsnl** [comment]
@gavinkflam good to see your back!
Are you interesting in adding me as a contributor to the project?
